apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-testing
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      serviceAccountName: deploy-access-sa
      containers:
        - name: httpd
          image: httpd
